project_id = "nrtuieysilnvegwsjxsa"

[functions.ai-chat]
verify_jwt = true

[functions.getPexelsImage]
verify_jwt = true

[functions.generate-itinerary]
verify_jwt = true

[functions.hotel-search]
verify_jwt = false
